### ISSUE TITLE
Ability to see if there is resources enough before deploying the edge/bare metal instance

### ISSUE THREAD

**Issue by wmariuss** [LumenTech/terraform-provider-lumen#10]
if i choose lare instance type i get error, with not clear message. Also, i could not see a data check if i can check if there is enough resources.

**Comment by wmariuss** [comment]
Cool.

**Comment by alifsarker** [comment]
@wmariuss We now have a data source called "lumen_bare_metal_configurations" that will give you the available instance types at a certain location. There are no errors currently using the existing instance types. 

Closing this issue as it has been resolved.
