### ISSUE TITLE
Error while  Network Instance Creation.

### ISSUE THREAD

**Issue by av-3nets** [LumenTech/terraform-provider-lumen#12]
Hi Team, 

I'm creating a network instance for Lumen edge computing using terraform. But facing below error
```
module.lumen_network.lumen_network_instance.tf_nw_test: Creating...
╷
│ Error: Cannot set property 'hostname' on null object
│ 
│   with module.lumen_network.lumen_network_instance.tf_nw_test,
│   on ../modules/create_resource_network_instance/main.tf line 3, in resource "lumen_network_instance" "tf_nw_test":
│    3: resource "lumen_network_instance" "tf_nw_test" {
│ 
╵
``` 

Provider version: v0.4.0
Terraform version: v1.2.4

Could you please help me here ?

**Comment by ShibayanC** [comment]
Can you cross-check if hostname is set or not?

**Comment by av-3nets** [comment]
There is no parameter named as hostname in terraform resource `lumen_network_instance`. I have referred this https://registry.terraform.io/providers/LumenTech/lumen/latest/docs/resources/resource_order_create_network_instance

**Comment by ShibayanC** [comment]
I meant - is the name for the instance defined in here (https://github.com/LumenTech/terraform-provider-lumen/blob/main/examples/create_resource_network_instance/terraform.tfvars#L8)? If you can send me the I would be able to help you out.

**Comment by av-3nets** [comment]
I have passed the network name. Please find the calling module files below:

`main.tf`
```
module "lumen_network" {
  source                   = "../modules/create_resource_network_instance"
  nw_instance_name         = var.network_name
  nw_instance_description  = var.network_description
  nw_group_id              = var.network_group_id
  nw_cloud_id              = var.network_cloud_id
  nw_plan_id               = var.network_plan_id
  nw_instance_type_code    = var.network_instance_type_code
  nw_instance_layout_id    = var.network_instance_layout_id
  nw_instance_location     = var.network_instance_location
  nw_instance_bandwidth    = var.network_instance_bandwidth
  nw_instance_network_type = var.network_instance_network_type
}
```

variables.tf
```
variable "lumen_username" {
  type        = string
  default     = ""
}

variable "lumen_password" {
  type        = string
  default     = ""
}

variable "lumen_api_access_token" {
  type        = string
  default     = ""
}

variable "lumen_api_refresh_token" {
  type        = string
  default     = ""
}

variable "network_name" {
  type        = string
  default     = ""
}

variable "network_description" {
  type        = string
  default     = ""
}

variable "network_group_id" {
  type        = string
  default     = ""
}

variable "network_cloud_id" {
  type        = string
  default     = ""
}

variable "network_plan_id" {
  type        = string
  default     = ""
}

variable "network_instance_type_code" {
  type        = string
  default     = ""
}

variable "network_instance_layout_id" {
  type        = string
  default     = ""
}

variable "network_instance_location" {
  type        = string
  default     = ""
}

variable "network_instance_bandwidth" {
  type        = string
  default     = ""
}

variable "network_instance_network_type" {
  type        = string
  default     = ""
}
```

`terraform.tfvars`
```
# Credentials and input parameters
lumen_username          = ""
lumen_password          = ""
lumen_api_access_token  = ""
lumen_api_refresh_token = ""

network_name                  = "sample"
network_description           = "This is for test"
network_group_id              = 1032
network_cloud_id              = 11
network_plan_id               = 1229
network_instance_type_code    = "ubuntu"
network_instance_layout_id    = 3904
network_instance_location     = "ALBYNYVPLEC"
network_instance_bandwidth    = 1
network_instance_network_type = "Internet"

```

**Comment by ShibayanC** [comment]
Refer to the example tf files for creating network instance (https://github.com/LumenTech/terraform-provider-lumen/tree/main/examples/create_resource_network_instance). Changing the variable names will not work, since that's what is defined and expected in the plugin code.

**Comment by ShibayanC** [comment]
Also, "network_instance_network_type" will be "EDGE_COMPUTE_INTERNET".

**Comment by av-3nets** [comment]
We are not changing the variable names, it is the calling module. Could you please check the root module file which I have attached and help me 

`main.tf`
```
# Terraform core utility
# The below configuration will create network instance and display result.
resource "lumen_network_instance" "tf_nw_test" {
  name        = var.nw_instance_name
  description = var.nw_instance_description

  group_id = var.nw_group_id
  cloud_id = var.nw_cloud_id
  plan_id  = var.nw_plan_id

  instance_type_code = var.nw_instance_type_code
  instance_layout_id = var.nw_instance_layout_id

  location     = var.nw_instance_location
  bandwidth    = var.nw_instance_bandwidth
  network_type = var.nw_instance_network_type

  tags = {
        name = "nw-tf-test"
    }

  labels = ["nw_tf_resource_test", "demo"]
}
```

Also I have used `EDGE_COMPUTE_INTERNET` for the `network_instance_network_type` variable but still facing the same issue

**Comment by av-3nets** [comment]
@ShibayanC Any update on the above ??

**Comment by ShibayanC** [comment]
@av-3nets I tried to reproduce the issue, didn't find any problem. Let me get back to you with an example terraform.tfvars that works for me.

**Comment by av-3nets** [comment]
@ShibayanC could you please share all the files used to create the network

**Comment by av-3nets** [comment]
@ShibayanC any update ?

**Comment by av-3nets** [comment]
@ShibayanC Could you please share us all the terraform files ?

**Comment by ShibayanC** [comment]
This will take some time, I'll try to get to it by early next week. Meanwhile you can refer to the example usage section, for both resources (https://github.com/LumenTech/terraform-provider-lumen/tree/main/docs/resources) and data sources (https://github.com/LumenTech/terraform-provider-lumen/tree/main/docs/data-sources) inside reference docs.

**Comment by ShibayanC** [comment]
@av-3nets Attached zipped 'client' ([client.zip](https://github.com/LumenTech/terraform-provider-lumen/files/9274404/client.zip)) has the terraform files, you can use the one that you need by renaming the appropriate ones to main.tf, variables.tf and terraform.tfvars. The provider.tf remains the same.

I tried creating a network instance and a bare metal instance again and it worked without issues. Can you give it another shot with the files attached and let me know?

**Comment by av-3nets** [comment]
Thank you @ShibayanC

**Comment by ShibayanC** [comment]
This issue is resolved.
