### ISSUE TITLE
Creating Network and BM Instance using the example coderesults in crash after Network is created

### ISSUE THREAD

**Issue by russctl** [LumenTech/terraform-provider-lumen#28]
Using the Code sample for 0.5.0, the Network was created, and I received an email confirming that, but the provider plugin crashed before creating the Bare Metal Instance. I did not build the provider locally but simply did the provider include and Terraform Init.
I am doing this on the internal environment and have created the same resources using the API, same input values, with success every time.

Message output from Terrafrom Apply was: 
╷
│ Error: Plugin did not respond
│
│   with lumen_network_instance.tf_nw_test,
│   on main.tf line 4, in resource "lumen_network_instance" "tf_nw_test":
│    4: resource "lumen_network_instance" "tf_nw_test" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-lumen_v0.5.0.exe plugin:

panic: interface conversion: interface {} is float64, not string

goroutine 67 [running]:
terraform-provider-lumen/lumen.SetNetworkInstanceCustomConfigs(0xc0007ff7c0, 0xc0000a2e80)
        terraform-provider-lumen/lumen/models.go:144 +0xb65
terraform-provider-lumen/lumen.ResourceNetworkInstanceRead(0x1359520, 0xc000313020, 0xc0000a2e80, 0x1090b20, 0xc0002c8dc0, 0x0, 0x0, 0x1)
        terraform-provider-lumen/lumen/resource_order_network_instance.go:341 +0x60f
terraform-provider-lumen/lumen.ResourceNetworkInstanceCreate(0x1359520, 0xc000313020, 0xc0000a2e80, 0x1090b20, 0xc0002c8dc0, 0xc00019b080, 0x6e3091, 0xc00063bc40)
        terraform-provider-lumen/lumen/resource_order_network_instance.go:288 +0x13ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0007ec380, 0x13594a0, 0xc0001aac00, 0xc0000a2e80, 0x1090b20, 0xc0002c8dc0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:330 +0x17e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007ec380, 0x13594a0, 0xc0001aac00, 0xc0007da930, 0xc00063bc40, 0x1090b20, 0xc0002c8dc0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x699
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000092ea0, 0x13594a0, 0xc0001aac00, 0xc0000eb360, 0xc0001aac00, 0xc000312700, 0x1369c40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8b9
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0006a49a0, 0x13594a0, 0xc0001aac00, 0xc0007da700, 0xc0006a49a0, 0xc0003976e0, 0xc000123ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x108fd60, 0xc0006a49a0, 0x1359560, 0xc0003976e0, 0xc000312780, 0x0, 0x1359560, 0xc0003976e0, 0xc0001acd80, 0x41a)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x21e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000252c40, 0x13661e0, 0xc000084600, 0xc000170400, 0xc0002ae900, 0x1adb9a0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x511
google.golang.org/grpc.(*Server).handleStream(0xc000252c40, 0x13661e0, 0xc000084600, 0xc000170400, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd04
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000306220, 0xc000252c40, 0x13661e0, 0xc000084600, 0xc000170400)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x20b

Error: The terraform-provider-lumen_v0.5.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by ShibayanC** [comment]
@russctl - Let me get back to you on this.

**Comment by ShibayanC** [comment]
@russctl - can you ping me when you're able, I want to get with you regarding this issue.

**Comment by alifsarker** [comment]
@russctl Since the rewrite of the Terraform provider, all of the examples are currently working. Feel free to try them out! Closing this issue as it has been resolved.
