### ISSUE TITLE
Feature: Add support for Mac using M2 CPU

### ISSUE THREAD

**Issue by robinostlund** [LumenTech/terraform-provider-lumen#57]
Hi,
Would you be able to add support for Mac using M2 CPU?

**Comment by nwang92** [comment]
+1, here's the error I'm getting when attempting to initialize the terraform provider:
```
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/lumentech/lumen v2.4.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

**Comment by alifsarker** [comment]
Thanks for your feedback. We are looking into this request to be able to support darwin_arm64.

**Comment by alifsarker** [comment]
While we look into testing the darwin_arm64 release, in the meantime you can try using the darwin_amd64 version of the release. M2 Macs have software emulation built in to be able to translate the machine code at runtime.

**Comment by alifsarker** [comment]
As of the latest release (v2.5.0), we now support M2 Macs with a darwin_arm64 version of the release moving forward.

**Comment by alifsarker** [comment]
As this issue has been resolved, I will be closing it. Thanks.
